encoding: utf-8
exclude:
  - CNAME
  - collect_contribs.py
  - README.md
  - regen_readme.py
  - requirements.txt
url: https://arhadthedev.net

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

compress_html:
  clippings: all
