name: Build

on:
  pull_request:
  workflow_call:

jobs:
  readme:
    name: Generate README
    runs-on: ubuntu-latest
    permissions:
      # setup-python access to check out code and install dependencies
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install the latest Python version
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: github_readme
          python-version: 3.13
      - name: Install dependencies
        working-directory: github_readme
        run: python -m pip install .
      - name: Gather contribution statistics
        # Call as a script to catch accidental resets of the POSIX execution bit
        run: >
          ./github_readme/collect_contribs.py \
            -rpython/cpython \
            -rpython/core-workflow \
            -rpython/bedevere \
            -rpython/devguide \
            -rpython/pyperformance \
            -rsphinx-contrib/sphinx-lint \
            -rtc39/ecma262 \
            -eoleg@arhadthedev.net \
            -edralife@yandex.ru \
            arhadthedev \
            > stats.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload raw statistics retrieved from GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Raw statistics from GitHub
          path: stats.json
      - name: Update README.md
        run: ./github_readme/regen_readme.py stats.json
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: README.md
          path: README.md

  site:
    name: Generate content for arhadthedev.net
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup GitHub Pages build tools
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
