name: Tests

on:
  pull_request:

jobs:
  check-actions:
    name: Check CI scripts with no execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      # From <https://github.com/rhysd/actionlint/blob/v1.7.7/docs/usage.md#problem-matchers>
      - name: Check Github Action YAML files with no execution
        run: |
          echo "::add-matcher::.github/problem-matchers/actionlint.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
  check-python:
    name: Check Python code with no execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install the latest Python version
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.11
      - name: Install tools
        run: python -m pip install wemake-python-styleguide
      - name: Test for code style
        # Ignore "WPS305 Found `f` string" 
        run: flake8 --ignore=WPS305 .
