name: Preview

on:
  pull_request:

env:
  CACHE_KEY: output-artifacts

jobs:
  generate:
    uses: ./.github/workflows/_generate.yml
    with:
      cache: ${{ env.CACHE_KEY }}

  update:
    name: Upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code and local actions
        uses: actions/checkout@v3
      - name: Take the regenerated file
        uses: actions/cache@v3
        with:
          path: README.md
          key: ${{ env.CACHE_KEY }}
      - name: Upload a generated README for debugging
        uses: actions/upload-artifact@v3
        with:
          name: README.md
          path: README.md
