name: Weekly Update

on:
  push:
    branches:
      - main
  schedule:
    # The string is composed using <https://crontab.guru/>
    - cron: '0 0 * * 1'

# For GitHub Pages (beta) action
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy-readme:
    name: Deploy README
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: README.md
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md contribution statistics

  deploy-site:
    name: Deploy arhadthedev.net
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Deploy the artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
