name: Weekly Update

on:
  push:
    branches:
      - main
  schedule:
    # The string is composed using <https://crontab.guru/>
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update:
    name: Commit changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install the latest Python version
        uses: actions/setup-python@v3
        with:
          cache: pip
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Gather contribution statistics
        run: >
          ./collect_contribs.py
            -rpython/cpython -rpython/core-workflow
            -rpython/bedevere
            -rsphinx-contrib/sphinx-lint
            -rtc39/ecma262 arhadthedev
            -eoleg@arhadthedev.net
            -edralife@yandex.ru
            arhadthedev
            > stats.json
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update README.md
        run: ./regen_readme.py stats.json
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md contribution statistics
