name: Monthly Update

on:
  push:
    branches:
      - main
  schedule:
    # The string is composed using <https://crontab.guru/>
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  deploy-readme:
    name: Deploy README
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: README.md
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update README.md contribution statistics

  deploy-site:
    name: Deploy arhadthedev.net
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    # As specified in <https://github.com/actions/starter-workflows/blob/4a8f18e34dd13d2b6ee4d8da2ba72629eafe1609/pages/jekyll-gh-pages.yml>
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Deploy the artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
