name: Weekly Update

on:
  push:
    branches:
      - main
  schedule:
    # The string is composed using <https://crontab.guru/>
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  update:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: README.md
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md contribution statistics
